/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Dynamic Evidence Checklist & Guide Component (PMK No. 2/2021)
 * Links Posita arguments directly to court evidence items (P-1 s.d. P-X).
 * Provides one-click Print/Download for all forms, statutory excerpts, guides, and step-by-step instructions.
 * 
 * TERMINOLOGY COMPLIANCE:
 * Strictly uses standard Indonesian: "legalisasi/pemeteraian di Kantor Pos" (zero prohibited terms).
 */

import React, { useState } from 'react';
import { 
  FileCheck, 
  Plus, 
  CheckCircle2, 
  Clock, 
  ArrowRight, 
  ArrowLeft, 
  HelpCircle, 
  ShieldCheck, 
  AlertCircle, 
  Stamp, 
  Layers, 
  FileText, 
  Scale, 
  Copy, 
  Check, 
  Trash2, 
  Edit3, 
  ChevronDown, 
  ChevronUp, 
  ExternalLink,
  BookOpen,
  Printer,
  Download,
  Briefcase,
  UserCheck,
  Building2,
  Package,
  Sparkles,
  Camera,
  FlaskConical
} from 'lucide-react';
import { EvidenceItem, EvidenceType, EvidenceStatus, EvidenceCategory, CaseRecord, DualAgentAssessment } from '../types';
import { DisclaimerBanner } from './DisclaimerBanner';
import { EvidenceCompletePacketModal } from './EvidenceCompletePacketModal';
import { 
  downloadEvidencePacketDoc, 
  printEvidencePacket, 
  printSimpleChecklist 
} from '../services/evidencePacketGenerator';

interface EvidenceGuideViewProps {
  activeCase: CaseRecord;
  evidenceItems: EvidenceItem[];
  assessment?: DualAgentAssessment | null;
  sectorName?: string;
  onUpdateEvidenceItem: (item: EvidenceItem) => void;
  onDeleteEvidenceItem?: (evidenceId: string) => void;
  onAddCustomEvidence: (item: Omit<EvidenceItem, 'id' | 'case_id' | 'created_at'>) => void;
  onProceedToDocument: () => void;
  onBackToAssessment: () => void;
}

export const EvidenceGuideView: React.FC<EvidenceGuideViewProps> = ({
  activeCase,
  evidenceItems,
  assessment,
  sectorName,
  onUpdateEvidenceItem,
  onDeleteEvidenceItem,
  onAddCustomEvidence,
  onProceedToDocument,
  onBackToAssessment,
}) => {
  const [showAddForm, setShowAddForm] = useState(false);
  const [filterCategory, setFilterCategory] = useState<string>('all');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [showTablePreview, setShowTablePreview] = useState(false);
  const [copiedTable, setCopiedTable] = useState(false);
  const [editingNoteId, setEditingNoteId] = useState<string | null>(null);
  const [tempNoteText, setTempNoteText] = useState('');
  const [expandedDetails, setExpandedDetails] = useState<Record<string, boolean>>({});
  
  // State for Complete Packet Modal & Downloads
  const [isPacketModalOpen, setIsPacketModalOpen] = useState(false);
  const [copiedStepId, setCopiedStepId] = useState<string | null>(null);
  const [downloadNotice, setDownloadNotice] = useState<string | null>(null);

  // Form State for Adding Custom Evidence
  const nextNumber = evidenceItems.length + 1;
  const [customKode, setCustomKode] = useState(`P-${nextNumber}`);
  const [customJenis, setCustomJenis] = useState<EvidenceType>('bukti_tertulis');
  const [customKategori, setCustomKategori] = useState<EvidenceCategory>('kerugian_faktual');
  const [customDeskripsi, setCustomDeskripsi] = useState('');
  const [customRelevansi, setCustomRelevansi] = useState('');
  const [customPosita, setCustomPosita] = useState('');
  const [customSyarat, setCustomSyarat] = useState('Wajib Legalisasi/Pemeteraian di Kantor Pos (Meterai Tempel Rp10.000 + Cap Pos)');

  const toggleDetail = (id: string) => {
    setExpandedDetails(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const handleProceedWithScroll = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    onProceedToDocument();
  };

  const handleBackWithScroll = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    onBackToAssessment();
  };

  // Helper to determine if an item can be generated by platform
  const isGeneratableDocument = (item: EvidenceItem): boolean => {
    const descLower = item.deskripsi.toLowerCase();
    return (
      descLower.includes('daftar bukti') ||
      descLower.includes('buku i') ||
      descLower.includes('buku ii') ||
      descLower.includes('draf permohonan') ||
      descLower.includes('surat pernyataan')
    );
  };

  const handleDirectPrintOrDownload = (item: EvidenceItem, mode: 'print' | 'download') => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    onProceedToDocument();
  };

  const handlePrintSimpleChecklist = () => {
    printSimpleChecklist(activeCase, evidenceItems, sectorName);
  };

  const handleDownloadAllPacket = () => {
    downloadEvidencePacketDoc(activeCase, evidenceItems, assessment, sectorName);
    setDownloadNotice('Berkas Paket Lengkap (.DOC) telah diunduh ke perangkat Anda.');
    setTimeout(() => setDownloadNotice(null), 4000);
  };

  const handlePrintAllPacket = () => {
    printEvidencePacket(activeCase, evidenceItems, assessment, sectorName);
  };

  const handleAddSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customDeskripsi.trim()) return;

    onAddCustomEvidence({
      kode: customKode.trim() || `P-${evidenceItems.length + 1}`,
      jenis: customJenis,
      kategori: customKategori,
      deskripsi: customDeskripsi.trim(),
      relevansi_hukum: customRelevansi.trim() || 'Mendukung uraian kerugian hak konstitusional pemohon dalam permohonan.',
      posita_dalil_terkait: customPosita.trim() || 'Posita: Hubungan Kausalitas dan Kerugian Aktual.',
      syarat_legalisasi: customSyarat,
      status: 'disarankan',
      catatan_pengguna: '',
    });

    setCustomDeskripsi('');
    setCustomRelevansi('');
    setCustomPosita('');
    setCustomKode(`P-${evidenceItems.length + 2}`);
    setShowAddForm(false);
  };

  const handleStatusChange = (item: EvidenceItem, newStatus: EvidenceStatus) => {
    const updated: EvidenceItem = {
      ...item,
      status: newStatus,
      updated_at: new Date().toISOString(),
    };
    onUpdateEvidenceItem(updated);
  };

  const handleCycleStatus = (item: EvidenceItem) => {
    let nextStatus: EvidenceStatus = 'sudah_disiapkan_user';
    if (item.status === 'disarankan') {
      nextStatus = 'sudah_disiapkan_user';
    } else if (item.status === 'sudah_disiapkan_user') {
      nextStatus = 'terverifikasi';
    } else {
      nextStatus = 'disarankan';
    }
    handleStatusChange(item, nextStatus);
  };

  const handleSaveNote = (item: EvidenceItem) => {
    const updated: EvidenceItem = {
      ...item,
      catatan_pengguna: tempNoteText.trim(),
      updated_at: new Date().toISOString(),
    };
    onUpdateEvidenceItem(updated);
    setEditingNoteId(null);
    setTempNoteText('');
  };

  const getJenisLabel = (jenis: EvidenceType) => {
    switch (jenis) {
      case 'bukti_tertulis':
        return 'Surat / Dokumen Tertulis';
      case 'keterangan_ahli':
        return 'Keterangan Ahli';
      case 'keterangan_saksi':
        return 'Keterangan Saksi Fakta';
      case 'petunjuk':
      default:
        return 'Petunjuk / Rekaman';
    }
  };

  const getKategoriLabel = (kategori?: EvidenceCategory) => {
    switch (kategori) {
      case 'legal_standing':
        return 'Legal Standing';
      case 'objek_pengujian':
        return 'Objek Norma UU';
      case 'kerugian_faktual':
        return 'Kerugian Faktual';
      case 'kausalitas':
        return 'Hubungan Kausalitas';
      case 'doktrin_ahli':
        return 'Kajian Ahli / Doktrin';
      default:
        return 'Bukti Pendukung';
    }
  };

  const getStatusBadge = (status: EvidenceStatus) => {
    switch (status) {
      case 'terverifikasi':
        return (
          <span className="inline-flex items-center gap-1 text-[11px] font-semibold bg-emerald-100 text-emerald-900 px-2.5 py-0.5 rounded-full border border-emerald-300">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-700" />
            <span>Siap & Lengkap</span>
          </span>
        );
      case 'sudah_disiapkan_user':
        return (
          <span className="inline-flex items-center gap-1 text-[11px] font-semibold bg-amber-100 text-amber-900 px-2.5 py-0.5 rounded-full border border-amber-300">
            <Clock className="w-3.5 h-3.5 text-amber-700" />
            <span>Sudah Disiapkan</span>
          </span>
        );
      case 'disarankan':
      default:
        return (
          <span className="inline-flex items-center gap-1 text-[11px] font-semibold bg-stone-100 text-stone-700 px-2.5 py-0.5 rounded-full border border-stone-300">
            <AlertCircle className="w-3.5 h-3.5 text-stone-500" />
            <span>Perlu Disiapkan</span>
          </span>
        );
      }
  };

  // Helper step-by-step guidance generator for self-prepared items
  const getStepByStepGuide = (item: EvidenceItem): { title: string; steps: string[]; tips: string } => {
    const desc = item.deskripsi.toLowerCase();
    if (desc.includes('ktp') || desc.includes('identitas')) {
      return {
        title: 'Panduan Fotokopi & Legalisasi KTP (Bukti Legal Standing):',
        steps: [
          'Bawa KTP asli ke tempat fotokopi. Minta fotokopi bolak-balik 2 sisi di bagian tengah 1 lembar kertas A4 (tidak boleh digunting kecil!). Buat sebanyak 12 rangkap.',
          'Beli meterai tempel Rp10.000,-. Tempelkan meterai pada lembar fotokopi pertama di samping tulisan fotokopi KTP.',
          'Bawa lembar fotokopi bermeterai tersebut ke loket Kantor Pos Besar terdekat.',
          'Katakan kepada petugas loket: "Mau minta legalisasi/pemeteraian kemudian untuk alat bukti persidangan Mahkamah Konstitusi".',
          'Petugas loket akan membubuhkan cap stempel pos resmi melintasi meterai tempel Rp10.000,-.'
        ],
        tips: 'Tuliskan "Bukti P-1" pada pojok kanan atas kertas setelah dilegalisir cap pos.'
      };
    }
    if (desc.includes('gaji') || desc.includes('rekening') || desc.includes('finansial') || desc.includes('penghasilan') || desc.includes('upah')) {
      return {
        title: 'Panduan Penyiapan Slip Gaji / Rekening Koran (Bukti Kerugian Faktual):',
        steps: [
          'Cetak slip gaji dari HRD/tempat kerja Anda atau minta rekening koran dari bank tempat Anda menerima gaji.',
          'Pastikan terdapat cap stempel basah atau tanda tangan resmi dari pihak penerbit.',
          'Fotokopi dokumen tersebut sebanyak 12 rangkap kertas A4.',
          'Tempelkan meterai tempel Rp10.000 pada lembar salinan utama dan mintakan cap legalisasi/pemeteraian di loket Kantor Pos.'
        ],
        tips: 'Gunakan stabilo untuk menandai angka pemotongan upah atau transaksi yang membuktikan kerugian Anda.'
      };
    }
    if (desc.includes('foto') || desc.includes('video') || desc.includes('lapangan') || desc.includes('rekaman')) {
      return {
        title: 'Panduan Pengambilan Foto & Rekaman Video (Standar Bukti MK):',
        steps: [
          'Aktifkan fitur GPS Location & Timestamp pada kamera smartphone Anda sebelum mengambil foto/video.',
          'Ambil dari 3 jarak: Jarak Jauh (landmark/plang nama), Jarak Sedang (lokasi umum), dan Jarak Dekat (kerusakan/dampak).',
          'Simpan file asli (jangan dikompres via WA) ke dalam Flashdisk / DVD-R.',
          'Cetak foto berwarna pada kertas A4 disertai keterangan tanggal, lokasi koordinat, dan nama pengambil foto.'
        ],
        tips: 'Gunakan lembar Berita Acara Penyerahan Bukti Digital yang disediakan pada paket platform.'
      };
    }
    if (desc.includes('uu') || desc.includes('undang-undang') || desc.includes('salinan uu')) {
      return {
        title: 'Panduan Salinan Undang-Undang (Objek Pengujian):',
        steps: [
          'Unduh salinan resmi Lembaran Negara RI dari portal Pasal.id atau gunakan berkas salinan dari platform ini.',
          'Cetak pasal yang diuji dan halaman pengesahan undang-undang sebanyak 12 rangkap.',
          'Tuliskan kode "Bukti P-2" di pojok kanan atas.',
          'Dokumen salinan lembaran negara resmi tidak memerlukan meterai pos karena merupakan produk hukum publik.'
        ],
        tips: 'Salinan resmi dari Pasal.id sudah siap cetak pada Paket Dokumen Lengkap platform.'
      };
    }
    if (desc.includes('lab') || desc.includes('sampel') || desc.includes('lingkungan') || desc.includes('audit')) {
      return {
        title: 'Panduan Uji Laboratorium & Sampel Kerugian:',
        steps: [
          'Ajukan permohonan uji laboratorium ke lembaga/lab terakreditasi KAN (ISO 17025) menggunakan draf formulir permohonan dari platform.',
          'Minta petugas pengambil sampel membuat Berita Acara Pengambilan Sampel (Chain of Custody).',
          'Fotokopi Sertifikat Hasil Uji (Certificate of Analysis) sebanyak 12 rangkap.',
          'Mintakan cap legalisasi/pemeteraian di Kantor Pos untuk salinan hasil uji lab.'
        ],
        tips: 'Sertakan keterangan dari petugas pengambil sampel sebagai bukti pendukung.'
      };
    }
    return {
      title: 'Panduan Penyiapan Dokumen & Pemeteraian di Kantor Pos:',
      steps: [
        'Siapkan dokumen asli dan fotokopi sebanyak 12 rangkap kertas A4.',
        'Tempelkan meterai tempel Rp10.000 pada lembar salinan utama di tempat yang tidak menutupi teks penting.',
        'Bawa berkas ke Kantor Pos Besar setempat untuk dimintakan cap legalisasi/pemeteraian bukti pengadilan.',
        'Tuliskan kode Bukti (misal: Bukti P-X) pada pojok kanan atas setiap berkas.'
      ],
      tips: 'Susun urutan berkas sesuai nomor urut Buku II Alat Bukti.'
    };
  };

  // Filtered evidence items
  const filteredItems = evidenceItems.filter((item) => {
    if (filterCategory !== 'all' && item.kategori !== filterCategory) return false;
    if (filterStatus !== 'all' && item.status !== filterStatus) return false;
    return true;
  });

  const totalItems = evidenceItems.length;
  const readyCount = evidenceItems.filter(
    (i) => i.status === 'sudah_disiapkan_user' || i.status === 'terverifikasi'
  ).length;
  const verifiedCount = evidenceItems.filter((i) => i.status === 'terverifikasi').length;
  const percentReady = totalItems > 0 ? Math.round((readyCount / totalItems) * 100) : 0;

  const copyTableToClipboard = () => {
    const headers = 'Kode Bukti\tJenis Bukti\tNama & Deskripsi Alat Bukti\tTujuan Pembuktian (Posita)\tSyarat Legalisasi\tStatus\n';
    const rows = evidenceItems
      .map(
        (i) =>
          `${i.kode}\t${getJenisLabel(i.jenis)}\t${i.deskripsi}\t${i.relevansi_hukum}\t${
            i.syarat_legalisasi || 'Legalisasi/Pemeteraian di Kantor Pos'
          }\t${i.status.replace(/_/g, ' ')}`
      )
      .join('\n');

    navigator.clipboard.writeText(headers + rows);
    setCopiedTable(true);
    setTimeout(() => setCopiedTable(false), 2500);
  };

  const handleCopySingleStep = (stepText: string, id: string) => {
    navigator.clipboard.writeText(stepText);
    setCopiedStepId(id);
    setTimeout(() => setCopiedStepId(null), 2500);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-8">
      {/* Header & Readiness Dashboard */}
      <div className="bg-white border-2 border-stone-300 rounded-lg p-6 sm:p-8 space-y-6 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-stone-200 pb-5">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-xs font-semibold text-rose-900 uppercase tracking-wider">
              <Scale className="w-4 h-4" />
              <span>Daftar Bukti Wajib Sidang MK</span>
            </div>
            <h1 className="font-serif text-2xl sm:text-3xl font-bold text-stone-900">
              Dokumen Bukti yang Perlu Anda Siapkan
            </h1>
            <p className="text-xs sm:text-sm text-stone-600">
              Periksa daftar dokumen di bawah ini. Centang yang sudah Anda miliki atau siapkan.
            </p>
          </div>

          <div className="bg-stone-50 border border-stone-300 p-4 rounded-lg text-right shrink-0 min-w-[200px] space-y-1">
            <div className="flex justify-between items-center text-xs text-stone-600">
              <span>Kesiapan Dokumen:</span>
              <span className="font-bold text-stone-900">{percentReady}%</span>
            </div>
            <div className="w-full bg-stone-200 h-2 rounded-full overflow-hidden">
              <div
                className="bg-emerald-600 h-full transition-all duration-300 rounded-full"
                style={{ width: `${percentReady}%` }}
              />
            </div>
            <div className="text-[11px] text-stone-500 flex justify-between pt-0.5">
              <span>{readyCount} dari {totalItems} disiapkan</span>
              <span className="font-medium text-emerald-700">{verifiedCount} lengkap</span>
            </div>
          </div>
        </div>

        {/* Sectoral Insight Banner */}
        <div className="bg-rose-50/70 border border-rose-200 rounded-md p-4 text-xs text-rose-950 flex items-start gap-3">
          <FileText className="w-5 h-5 text-rose-900 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <div className="font-semibold text-rose-900 flex items-center gap-2">
              <span>Fokus Kasus Anda:</span>
              <span className="bg-rose-100 text-rose-900 px-2 py-0.5 rounded text-[11px] font-bold border border-rose-300">
                {sectorName || 'Kerugian Hak Konstitusional Pemohon'}
              </span>
            </div>
            <p className="text-rose-900/90 leading-relaxed">
              Seluruh fotokopi bukti surat wajib ditempel meterai Rp10.000 dan dimintakan cap <strong>legalisasi/pemeteraian di Kantor Pos</strong> sebelum dibawa ke sidang Mahkamah Konstitusi.
            </p>
          </div>
        </div>

        {/* POIN MANDAT REQUEST: ACTION BAR PRINT SEMUA & DOWNLOAD SEMUA DI BAWAH BOX FOKUS KASUS ANDA */}
        <div className="bg-stone-900 text-white rounded-lg p-5 sm:p-6 space-y-4 shadow-md border border-stone-800">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-bold text-rose-300 uppercase tracking-wider">
              <Package className="w-4 h-4 text-rose-400 shrink-0" />
              <span>Paket Dokumen & Panduan Lengkap (Aksesibilitas Warga)</span>
            </div>
            <h3 className="font-serif font-bold text-lg sm:text-xl text-white">
              Cetak atau Unduh Seluruh Dokumen & Panduan Sekaligus
            </h3>
            <p className="text-xs sm:text-sm text-stone-300 leading-relaxed max-w-3xl">
              Mencakup lembar checklist fisik, salinan UU resmi dari Pasal.id, formulir pengaduan instansi, formulir permohonan uji lab, panduan pengambilan foto/video berstandar bukti MK, serta step-by-step fotokopi hingga legalisasi Kantor Pos.
            </p>
            {downloadNotice && (
              <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-300 bg-emerald-950/80 border border-emerald-700 px-3 py-1 rounded mt-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                <span>{downloadNotice}</span>
              </div>
            )}
          </div>

          <div className="pt-2 border-t border-stone-800/80 flex flex-wrap items-center gap-2.5 sm:gap-3">
            <button
              onClick={handleDownloadAllPacket}
              className="flex-1 sm:flex-initial px-4 py-2.5 bg-stone-800 hover:bg-stone-700 text-white rounded-md text-xs sm:text-sm font-semibold flex items-center justify-center gap-2 border border-stone-600 transition shadow-xs cursor-pointer active:scale-95 whitespace-nowrap"
              title="Unduh langsung berkas Word (.DOC) berisi seluruh dokumen, formulir, dan panduan lengkap"
            >
              <Download className="w-4 h-4 text-rose-300 shrink-0" />
              <span>Download Semua (.DOC / Berkas)</span>
            </button>
            <button
              onClick={handlePrintAllPacket}
              className="flex-1 sm:flex-initial px-4 py-2.5 bg-[#881337] hover:bg-[#70102e] text-white rounded-md text-xs sm:text-sm font-semibold flex items-center justify-center gap-2 transition shadow-xs border border-rose-900 cursor-pointer active:scale-95 whitespace-nowrap"
              title="Cetak langsung seluruh paket dokumen dan panduan siap bawa tanpa halaman kosong"
            >
              <Printer className="w-4 h-4 shrink-0" />
              <span>Print Semua Panduan & Berkas</span>
            </button>
            <button
              onClick={() => setIsPacketModalOpen(true)}
              className="px-3.5 py-2.5 bg-stone-950 hover:bg-stone-800 text-stone-300 hover:text-white rounded-md text-xs sm:text-sm font-medium flex items-center justify-center gap-1.5 border border-stone-700 transition cursor-pointer whitespace-nowrap"
              title="Buka jendela pratinjau interaktif per kategori"
            >
              <BookOpen className="w-3.5 h-3.5 shrink-0" />
              <span>Pratinjau / Salin Teks</span>
            </button>
          </div>
        </div>
      </div>

      {/* Quick Jump: Duplicate 'Buat Dokumen Resmi' button directly below the top box */}
      <div className="bg-stone-100/90 border border-stone-300/80 rounded-lg p-3.5 sm:p-4 flex flex-col sm:flex-row items-center justify-between gap-3 shadow-xs">
        <div className="flex items-center gap-2.5 text-stone-800 text-xs sm:text-sm">
          <FileCheck className="w-4 h-4 sm:w-5 sm:h-5 text-rose-900 shrink-0" />
          <span className="font-medium text-stone-700">
            Ingin langsung membuat draf berkas permohonan tanpa membaca seluruh daftar bukti?
          </span>
        </div>
        <button
          onClick={handleProceedWithScroll}
          className="w-full sm:w-auto shrink-0 bg-[#881337] hover:bg-[#70102e] text-white px-5 py-2.5 rounded-md text-xs sm:text-sm font-semibold transition flex items-center justify-center gap-2 shadow-xs border border-rose-900 cursor-pointer active:scale-95 whitespace-nowrap"
        >
          <span>Buat Dokumen Resmi</span>
          <ArrowRight className="w-4 h-4 shrink-0" />
        </button>
      </div>

      <DisclaimerBanner compact />

      {/* Main Evidence Checklist Section */}
      <div className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h2 className="font-serif font-bold text-xl text-stone-900">
              Daftar Dokumen
            </h2>
            <p className="text-xs text-stone-600">
              Klik tanda centang jika dokumen sudah siap di tangan Anda.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowTablePreview(!showTablePreview)}
              className="px-3 py-1.5 border border-stone-300 rounded text-xs font-semibold text-stone-700 bg-white hover:bg-stone-100 transition flex items-center gap-1.5 cursor-pointer"
            >
              <BookOpen className="w-3.5 h-3.5 text-stone-600" />
              <span>{showTablePreview ? 'Tutup Format MK' : 'Lihat Format Resmi MK (Buku II)'}</span>
            </button>

            <button
              onClick={() => setShowAddForm(!showAddForm)}
              className="bg-[#881337] hover:bg-[#70102e] text-white px-3.5 py-1.5 rounded text-xs font-semibold transition flex items-center gap-1.5 shadow-xs cursor-pointer"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>{showAddForm ? 'Tutup Form' : 'Tambah Bukti'}</span>
            </button>
          </div>
        </div>

        {/* Filter Pills (Simple) */}
        <div className="flex flex-wrap items-center gap-2 pt-1 border-b border-stone-200 pb-3">
          <span className="text-xs text-stone-500 font-medium mr-1">Filter:</span>
          {[
            { id: 'all', label: 'Semua Dokumen' },
            { id: 'legal_standing', label: 'Identitas & Standing' },
            { id: 'objek_pengujian', label: 'Salinan UU' },
            { id: 'kerugian_faktual', label: 'Bukti Kerugian' },
            { id: 'kausalitas', label: 'Bukti Dampak' },
          ].map((cat) => (
            <button
              key={cat.id}
              onClick={() => setFilterCategory(cat.id)}
              className={`px-2.5 py-1 rounded text-xs font-medium transition cursor-pointer ${
                filterCategory === cat.id
                  ? 'bg-stone-900 text-white'
                  : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
              }`}
            >
              {cat.label}
            </button>
          ))}

          <div className="ml-auto flex items-center gap-1 text-xs">
            <span className="text-stone-500">Status:</span>
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
              className="px-2 py-1 border border-stone-300 rounded text-xs bg-white text-stone-800"
            >
              <option value="all">Semua Status</option>
              <option value="disarankan">Perlu Disiapkan</option>
              <option value="sudah_disiapkan_user">Sudah Disiapkan</option>
              <option value="terverifikasi">Siap & Lengkap</option>
            </select>
          </div>
        </div>

        {/* Add Evidence Form */}
        {showAddForm && (
          <form onSubmit={handleAddSubmit} className="bg-stone-50 border border-stone-300 rounded-lg p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-stone-200 pb-2">
              <span className="font-bold text-xs text-stone-900 uppercase">Tambah Dokumen Alat Bukti Baru</span>
              <button
                type="button"
                onClick={() => setShowAddForm(false)}
                className="text-stone-400 hover:text-stone-600 text-xs cursor-pointer"
              >
                Batal
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Kode Bukti:</label>
                <input
                  type="text"
                  value={customKode}
                  onChange={(e) => setCustomKode(e.target.value)}
                  className="w-full px-2.5 py-1.5 border border-stone-300 rounded text-xs bg-white"
                  placeholder="Misal: P-5"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Jenis Bukti:</label>
                <select
                  value={customJenis}
                  onChange={(e) => setCustomJenis(e.target.value as EvidenceType)}
                  className="w-full px-2.5 py-1.5 border border-stone-300 rounded text-xs bg-white"
                >
                  <option value="bukti_tertulis">Surat / Dokumen Tertulis</option>
                  <option value="keterangan_ahli">Keterangan Ahli</option>
                  <option value="keterangan_saksi">Keterangan Saksi Fakta</option>
                  <option value="petunjuk">Petunjuk / Rekaman</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Kategori Bukti:</label>
                <select
                  value={customKategori}
                  onChange={(e) => setCustomKategori(e.target.value as EvidenceCategory)}
                  className="w-full px-2.5 py-1.5 border border-stone-300 rounded text-xs bg-white"
                >
                  <option value="legal_standing">Identitas / Standing</option>
                  <option value="objek_pengujian">Objek Norma UU</option>
                  <option value="kerugian_faktual">Kerugian Faktual</option>
                  <option value="kausalitas">Hubungan Kausalitas</option>
                  <option value="doktrin_ahli">Doktrin / Kajian</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-stone-700 mb-1">Nama / Deskripsi Dokumen Bukti:</label>
              <input
                type="text"
                value={customDeskripsi}
                onChange={(e) => setCustomDeskripsi(e.target.value)}
                placeholder="Contoh: Surat Peringatan PHK, Kwitansi Pembayaran, atau Laporan Uji Lab Lingkungan"
                required
                className="w-full px-3 py-1.5 border border-stone-300 rounded text-xs bg-white"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Tujuan Pembuktian (Relevansi):</label>
                <input
                  type="text"
                  value={customRelevansi}
                  onChange={(e) => setCustomRelevansi(e.target.value)}
                  placeholder="Membuktikan pemutusan hubungan kerja tanpa pesangon sesuai pasal UU"
                  className="w-full px-3 py-1.5 border border-stone-300 rounded text-xs bg-white"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Keterkaitan Dalil Posita:</label>
                <input
                  type="text"
                  value={customPosita}
                  onChange={(e) => setCustomPosita(e.target.value)}
                  placeholder="Posita: Uraian Kerugian Aktual Paragraf 12"
                  className="w-full px-3 py-1.5 border border-stone-300 rounded text-xs bg-white"
                />
              </div>
            </div>

            <div className="flex justify-end pt-1">
              <button
                type="submit"
                className="bg-[#881337] hover:bg-[#70102e] text-white px-4 py-1.5 rounded text-xs font-semibold transition cursor-pointer"
              >
                Simpan Bukti Baru
              </button>
            </div>
          </form>
        )}

        {/* Evidence Table Preview (Buku II Format MK) */}
        {showTablePreview && (
          <div className="bg-stone-50 border border-stone-300 rounded-lg p-4 space-y-3">
            <div className="flex items-center justify-between border-b border-stone-200 pb-2">
              <div className="flex items-center gap-2">
                <BookOpen className="w-4 h-4 text-stone-700" />
                <span className="font-bold text-xs text-stone-900">Format Resmi Lampiran Buku II Alat Bukti MK</span>
              </div>
              <button
                onClick={copyTableToClipboard}
                className="text-xs bg-white border border-stone-300 hover:bg-stone-100 text-stone-700 px-2.5 py-1 rounded flex items-center gap-1 cursor-pointer"
              >
                {copiedTable ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedTable ? 'Tersalin' : 'Salin Tabel'}</span>
              </button>
            </div>

            <div className="overflow-x-auto bg-white rounded border border-stone-200">
              <table className="w-full text-xs text-left border-collapse">
                <thead>
                  <tr className="bg-stone-100 border-b border-stone-200 text-stone-800">
                    <th className="p-2 border-r border-stone-200 w-16 text-center">Kode</th>
                    <th className="p-2 border-r border-stone-200 w-32">Jenis</th>
                    <th className="p-2 border-r border-stone-200">Nama & Deskripsi Alat Bukti</th>
                    <th className="p-2 border-r border-stone-200">Keterkaitan Posita</th>
                    <th className="p-2 border-r border-stone-200 w-36">Syarat Legalisasi</th>
                    <th className="p-2 w-28 text-center">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-stone-200">
                  {evidenceItems.map((item) => (
                    <tr key={item.id} className="hover:bg-stone-50">
                      <td className="p-2 border-r border-stone-200 font-mono font-bold text-center text-[#881337]">{item.kode}</td>
                      <td className="p-2 border-r border-stone-200">{getJenisLabel(item.jenis)}</td>
                      <td className="p-2 border-r border-stone-200">
                        <span className="font-semibold text-stone-900 block">{item.deskripsi}</span>
                        <span className="text-[11px] text-stone-500">{item.relevansi_hukum}</span>
                      </td>
                      <td className="p-2 border-r border-stone-200 text-stone-600">{item.posita_dalil_terkait || '-'}</td>
                      <td className="p-2 border-r border-stone-200 text-[11px] text-stone-600">{item.syarat_legalisasi || 'Legalisasi di Kantor Pos'}</td>
                      <td className="p-2 text-center">{getStatusBadge(item.status)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Evidence Items List */}
        <div className="space-y-3">
          {filteredItems.length === 0 ? (
            <div className="p-8 text-center bg-stone-50 border border-stone-200 rounded-lg text-xs text-stone-500">
              Tidak ada dokumen bukti yang sesuai dengan filter yang dipilih.
            </div>
          ) : (
            filteredItems.map((item) => {
              const isReady = item.status === 'sudah_disiapkan_user' || item.status === 'terverifikasi';
              const isVerified = item.status === 'terverifikasi';
              const isExpanded = !!expandedDetails[item.id];
              const isEditingNote = editingNoteId === item.id;
              const canGenerate = isGeneratableDocument(item);
              const guide = getStepByStepGuide(item);

              return (
                <div
                  key={item.id}
                  className={`bg-white border rounded-lg p-4 sm:p-5 transition shadow-xs space-y-3 ${
                    isVerified
                      ? 'border-emerald-300 bg-emerald-50/15'
                      : isReady
                      ? 'border-amber-300 bg-amber-50/15'
                      : 'border-stone-200 hover:border-stone-300'
                  }`}
                >
                  {/* Top Simple Row: Checkbox, Clean Document Name, Action Buttons / Badge */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div className="flex items-start sm:items-center gap-3">
                      {/* Checkbox toggle */}
                      <button
                        onClick={() => handleCycleStatus(item)}
                        className={`w-6 h-6 rounded-md flex items-center justify-center border transition shrink-0 mt-0.5 sm:mt-0 cursor-pointer ${
                          isVerified
                            ? 'bg-emerald-700 text-white border-emerald-700'
                            : isReady
                            ? 'bg-amber-600 text-white border-amber-600'
                            : 'border-stone-400 bg-white hover:border-stone-600'
                        }`}
                        title="Klik untuk mengubah status kesiapan dokumen"
                      >
                        {isVerified || isReady ? <Check className="w-4 h-4 stroke-[3]" /> : null}
                      </button>

                      <div>
                        {/* Clean actionable document title */}
                        <h3 className="font-serif font-bold text-base text-stone-900 leading-snug">
                          {item.deskripsi}
                        </h3>
                        <p className="text-xs text-stone-600 mt-0.5">
                          {item.relevansi_hukum}
                        </p>
                      </div>
                    </div>

                    {/* Right side: Action Buttons */}
                    <div className="flex items-center gap-2 shrink-0 ml-9 sm:ml-0">
                      {canGenerate ? (
                        <div className="flex items-center gap-1.5">
                          <button
                            onClick={() => handleDirectPrintOrDownload(item, 'print')}
                            className="px-2.5 py-1 bg-stone-900 hover:bg-stone-800 text-white rounded text-xs font-medium flex items-center gap-1 shadow-2xs transition cursor-pointer"
                            title="Cetak dokumen ini langsung"
                          >
                            <Printer className="w-3.5 h-3.5" />
                            <span>Print</span>
                          </button>
                          <button
                            onClick={() => handleDirectPrintOrDownload(item, 'download')}
                            className="px-2.5 py-1 bg-[#881337] hover:bg-[#70102e] text-white rounded text-xs font-medium flex items-center gap-1 shadow-2xs transition cursor-pointer"
                            title="Unduh draf dokumen ini"
                          >
                            <Download className="w-3.5 h-3.5" />
                            <span>Download</span>
                          </button>
                        </div>
                      ) : (
                        <div className="flex items-center gap-1.5">
                          <button
                            onClick={() => toggleDetail(item.id)}
                            className="text-[11px] font-semibold bg-rose-50 text-rose-900 hover:bg-rose-100 px-2.5 py-1 rounded-md border border-rose-300 flex items-center gap-1 transition cursor-pointer"
                            title="Lihat panduan lengkap fotokopi hingga legalisasi pos"
                          >
                            <Stamp className="w-3 h-3 text-rose-800" />
                            <span>Panduan Langkah</span>
                          </button>
                        </div>
                      )}

                      {/* Status indicator */}
                      {getStatusBadge(item.status)}
                    </div>
                  </div>

                  {/* Toggle Accordion: "Lihat Detail" */}
                  <div className="border-t border-stone-100 pt-2 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <button
                      type="button"
                      onClick={() => toggleDetail(item.id)}
                      className="text-stone-600 hover:text-stone-900 font-medium flex items-center gap-1 cursor-pointer"
                    >
                      <span>{isExpanded ? 'Tutup Panduan & Detail' : 'Lihat Panduan Step-by-Step & Detail Hukum'}</span>
                      {isExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                    </button>

                    <div className="flex items-center gap-3">
                      {item.catatan_pengguna && !isEditingNote && (
                        <span className="text-[11px] text-stone-500 italic truncate max-w-xs">
                          Catatan: {item.catatan_pengguna}
                        </span>
                      )}

                      <button
                        onClick={() => {
                          setEditingNoteId(item.id);
                          setTempNoteText(item.catatan_pengguna || '');
                        }}
                        className="text-[11px] text-rose-900 hover:underline font-medium cursor-pointer"
                      >
                        {item.catatan_pengguna ? 'Ubah Catatan' : '+ Catatan'}
                      </button>

                      {onDeleteEvidenceItem && (
                        <button
                          onClick={() => onDeleteEvidenceItem(item.id)}
                          title="Hapus Dokumen Ini"
                          className="text-stone-400 hover:text-rose-700 p-0.5 transition cursor-pointer"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  </div>

                  {/* Note Editing Input */}
                  {isEditingNote && (
                    <div className="p-3 bg-stone-50 rounded border border-stone-200 space-y-2 text-xs">
                      <label className="block text-[11px] font-semibold text-stone-700">
                        Catatan Lokasi Fisik / Status Dokumen:
                      </label>
                      <input
                        type="text"
                        value={tempNoteText}
                        onChange={(e) => setTempNoteText(e.target.value)}
                        placeholder="Contoh: Fotokopi asli disimpan di map kuning, sudah dilegalisir di Kantor Pos."
                        className="w-full px-3 py-1.5 border border-stone-300 rounded text-xs bg-white focus:outline-none focus:ring-1 focus:ring-rose-800"
                      />
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleSaveNote(item)}
                          className="bg-stone-900 text-white px-3 py-1 rounded text-xs font-semibold hover:bg-stone-800 cursor-pointer"
                        >
                          Simpan Catatan
                        </button>
                        <button
                          onClick={() => setEditingNoteId(null)}
                          className="border border-stone-300 text-stone-700 px-3 py-1 rounded text-xs hover:bg-stone-100 cursor-pointer"
                        >
                          Batal
                        </button>
                      </div>
                    </div>
                  )}

                  {/* Comprehensive Step-by-Step & Technical Detail Accordion */}
                  {isExpanded && (
                    <div className="mt-2 p-4 bg-stone-50 border border-stone-200 rounded-md space-y-3.5 text-xs text-stone-800">
                      
                      {/* Step-by-Step Box (Feeding Total ke Warga) */}
                      <div className="bg-white border border-rose-200 rounded-md p-3.5 space-y-2.5 shadow-2xs">
                        <div className="flex items-center justify-between border-b border-stone-200 pb-1.5">
                          <div className="flex items-center gap-2 font-bold text-stone-900">
                            <Stamp className="w-4 h-4 text-[#881337]" />
                            <span>{guide.title}</span>
                          </div>
                          <button
                            onClick={() => handleCopySingleStep(guide.steps.join('\n'), item.id)}
                            className="text-[11px] text-stone-600 hover:text-stone-900 flex items-center gap-1 bg-stone-100 px-2 py-0.5 rounded border border-stone-300 cursor-pointer"
                          >
                            {copiedStepId === item.id ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                            <span>{copiedStepId === item.id ? 'Tersalin' : 'Salin Langkah'}</span>
                          </button>
                        </div>

                        <ol className="list-decimal pl-5 space-y-1.5 text-stone-700 leading-relaxed text-xs">
                          {guide.steps.map((step, sIdx) => (
                            <li key={sIdx}>{step}</li>
                          ))}
                        </ol>

                        {guide.tips && (
                          <div className="mt-2 p-2 bg-amber-50 rounded border border-amber-200 text-[11px] text-amber-900 font-medium">
                            💡 <strong>Tip Praktis:</strong> {guide.tips}
                          </div>
                        )}
                      </div>

                      {/* Technical Legal Metadata */}
                      <div className="pt-1 space-y-2 text-xs">
                        <div className="flex flex-wrap items-center gap-2 border-b border-stone-200 pb-2">
                          <span className="font-mono font-bold text-xs bg-stone-900 text-white px-2 py-0.5 rounded">
                            Kode: {item.kode}
                          </span>
                          <span className="bg-rose-50 text-rose-900 border border-rose-200 px-2 py-0.5 rounded font-semibold text-[11px]">
                            Kategori: {getKategoriLabel(item.kategori)}
                          </span>
                          <span className="bg-stone-100 text-stone-700 px-2 py-0.5 rounded border border-stone-300 text-[11px]">
                            Jenis: {getJenisLabel(item.jenis)}
                          </span>
                        </div>

                        <div className="space-y-1">
                          <div className="flex items-center gap-1.5 font-semibold text-stone-900">
                            <Scale className="w-3.5 h-3.5 text-rose-900 shrink-0" />
                            <span>Keterkaitan Dalil Posita:</span>
                          </div>
                          <p className="text-stone-700 pl-5">
                            {item.posita_dalil_terkait || 'Membuktikan kerugian hak konstitusional pemohon secara faktual.'}
                          </p>
                        </div>

                        <div className="space-y-1">
                          <div className="flex items-center gap-1.5 font-semibold text-stone-900">
                            <Stamp className="w-3.5 h-3.5 text-rose-900 shrink-0" />
                            <span>Syarat Formal Legalisasi:</span>
                          </div>
                          <p className="text-stone-700 pl-5">
                            {item.syarat_legalisasi || 'Wajib Legalisasi/Pemeteraian di Kantor Pos (Meterai Tempel Rp10.000 + Cap Pos)'}
                          </p>
                        </div>

                        {item.url_rujukan_pasal_id && (
                          <div className="pt-1">
                            <a
                              href={item.url_rujukan_pasal_id}
                              target="_blank"
                              rel="noreferrer noopener"
                              className="inline-flex items-center gap-1 text-[11px] font-semibold text-indigo-700 hover:text-indigo-900 bg-indigo-50 border border-indigo-200 px-2 py-0.5 rounded transition"
                            >
                              <span>Lihat Rujukan di Pasal.id</span>
                              <ExternalLink className="w-3 h-3" />
                            </a>
                          </div>
                        )}
                      </div>

                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>
      </div>

      {/* Printable Simple Checklist (Alat Bantu Fisik Warga) */}
      <div className="bg-white border-2 border-stone-300 rounded-lg p-6 space-y-4 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-stone-200 pb-3">
          <div>
            <h3 className="font-serif font-bold text-base text-stone-900 flex items-center gap-2">
              <Printer className="w-4 h-4 text-stone-700" />
              <span>Daftar Bukti Siap Cetak (Panduan Fisik Warga)</span>
            </h3>
            <p className="text-xs text-stone-600">
              Cetak lembar checklist sederhana ini untuk Anda bawa saat mengumpulkan dan mengecek berkas fotokopi di rumah atau ke Kantor Pos.
            </p>
          </div>
          <button
            onClick={handlePrintSimpleChecklist}
            className="px-4 py-2 bg-stone-900 hover:bg-stone-800 text-white rounded text-xs font-semibold flex items-center justify-center gap-1.5 shadow-xs transition cursor-pointer shrink-0"
          >
            <Printer className="w-4 h-4" />
            <span>Cetak Lembar Checklist</span>
          </button>
        </div>

        <div className="bg-stone-50 border border-stone-200 rounded p-4 space-y-2">
          <div className="text-xs font-semibold text-stone-800 border-b border-stone-200 pb-1 flex justify-between">
            <span>Nama Dokumen yang Harus Disiapkan</span>
            <span className="text-stone-500">Cek Fisik</span>
          </div>
          <div className="divide-y divide-stone-200">
            {evidenceItems.map((item, idx) => (
              <div key={item.id} className="py-2 flex items-center justify-between text-xs text-stone-800">
                <div className="flex items-center gap-2 pr-4">
                  <span className="text-stone-400 font-mono w-5">{idx + 1}.</span>
                  <span className="font-medium text-stone-900">{item.deskripsi}</span>
                </div>
                <div className="w-5 h-5 border-2 border-stone-400 rounded shrink-0 bg-white" />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Lawyer Marketplace Mockup (Bursa Lawyer Pro Bono & Terverifikasi) */}
      <div className="bg-white border-2 border-stone-300 rounded-lg p-6 space-y-5 shadow-xs">
        <div className="border-b border-stone-200 pb-3 space-y-1">
          <div className="flex items-center gap-2 text-xs font-semibold text-rose-900 uppercase tracking-wider">
            <Briefcase className="w-4 h-4" />
            <span>Dukungan Advokat & Bantuan Hukum</span>
          </div>
          <h3 className="font-serif font-bold text-xl text-stone-900">
            Butuh Pendampingan Advokat Resmi di Sidang MK?
          </h3>
          <p className="text-xs text-stone-600 leading-relaxed">
            Meskipun Anda berhak maju sendiri tanpa pengacara, Anda dapat terhubung dengan Lembaga Bantuan Hukum (LBH) mitra dan advokat konstitusi pro bono untuk pendampingan persidangan di Mahkamah Konstitusi.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Lawyer Card 1 */}
          <div className="bg-stone-50 border border-stone-200 rounded-lg p-4 space-y-3 flex flex-col justify-between">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold bg-emerald-100 text-emerald-900 px-2 py-0.5 rounded border border-emerald-300">
                  Pro Bono (Gratis)
                </span>
                <span className="text-[11px] text-stone-500 font-medium">BEM FH UI & LBH</span>
              </div>
              <div>
                <h4 className="font-serif font-bold text-sm text-stone-900">Posko Bantuan Hukum Konstitusi</h4>
                <p className="text-xs text-stone-600">Spesialisasi: Hak Asasi, Lingkungan & Ketenagakerjaan</p>
              </div>
              <p className="text-[11px] text-stone-500 leading-relaxed">
                Pendampingan penyusunan permohonan dan asistensi berkas bukti untuk warga/kelompok rentan.
              </p>
            </div>
            <button
              disabled
              title="Fitur segera hadir pada rilis berikutnya"
              className="w-full mt-2 py-2 px-3 bg-stone-200 text-stone-500 rounded text-xs font-semibold cursor-not-allowed border border-stone-300"
            >
              Hubungi (Segera Hadir)
            </button>
          </div>

          {/* Lawyer Card 2 */}
          <div className="bg-stone-50 border border-stone-200 rounded-lg p-4 space-y-3 flex flex-col justify-between">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold bg-emerald-100 text-emerald-900 px-2 py-0.5 rounded border border-emerald-300">
                  Pro Bono (Gratis)
                </span>
                <span className="text-[11px] text-stone-500 font-medium">Advokat Publik</span>
              </div>
              <div>
                <h4 className="font-serif font-bold text-sm text-stone-900">Klinik Hukum Tata Negara</h4>
                <p className="text-xs text-stone-600">Spesialisasi: Uji Materiil UU & Hak Pemilih</p>
              </div>
              <p className="text-[11px] text-stone-500 leading-relaxed">
                Asistensi pengujian norma undang-undang yang bertentangan dengan UUD 1945.
              </p>
            </div>
            <button
              disabled
              title="Fitur segera hadir pada rilis berikutnya"
              className="w-full mt-2 py-2 px-3 bg-stone-200 text-stone-500 rounded text-xs font-semibold cursor-not-allowed border border-stone-300"
            >
              Hubungi (Segera Hadir)
            </button>
          </div>

          {/* Lawyer Card 3 */}
          <div className="bg-stone-50 border border-stone-200 rounded-lg p-4 space-y-3 flex flex-col justify-between">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-[11px] font-bold bg-stone-200 text-stone-800 px-2 py-0.5 rounded border border-stone-300">
                  Konsultasi Mandiri
                </span>
                <span className="text-[11px] text-stone-500 font-medium">Mitra Kantor Hukum</span>
              </div>
              <div>
                <h4 className="font-serif font-bold text-sm text-stone-900">Advokat Litigasi Konstitusi</h4>
                <p className="text-xs text-stone-600">Spesialisasi: Hukum Bisnis, Sumber Daya & Pajak</p>
              </div>
              <p className="text-[11px] text-stone-500 leading-relaxed">
                Konsultasi penyusunan argumentasi hukum dan kuasa hukum di ruang sidang MKRI.
              </p>
            </div>
            <button
              disabled
              title="Fitur segera hadir pada rilis berikutnya"
              className="w-full mt-2 py-2 px-3 bg-stone-200 text-stone-500 rounded text-xs font-semibold cursor-not-allowed border border-stone-300"
            >
              Hubungi (Segera Hadir)
            </button>
          </div>
        </div>
      </div>

      {/* Practical Guide Section (PMK No. 2/2021 & UU Bea Meterai) */}
      <div className="bg-stone-50 border-2 border-stone-300 rounded-lg p-6 space-y-4">
        <div className="flex items-center gap-2 text-stone-900">
          <HelpCircle className="w-5 h-5 text-rose-900 shrink-0" />
          <h3 className="font-serif font-bold text-base">
            Panduan Resmi Beracara & Validasi Pembuktian Mahkamah Konstitusi
          </h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="bg-white border border-stone-200 rounded-md p-4 space-y-2">
            <div className="font-bold text-stone-900 flex items-center gap-1.5">
              <Stamp className="w-4 h-4 text-rose-800" />
              <span>1. Legalisasi / Pemeteraian di Kantor Pos</span>
            </div>
            <p className="text-stone-700 leading-relaxed">
              Berdasarkan UU Bea Meterai dan tata tertib persidangan MK, seluruh fotokopi alat bukti surat <strong>wajib ditempeli meterai tempel Rp10.000,-</strong> dan dimintakan cap legalisasi/pemeteraian di loket Kantor Pos terdekat sebelum persidangan.
            </p>
          </div>

          <div className="bg-white border border-stone-200 rounded-md p-4 space-y-2">
            <div className="font-bold text-stone-900 flex items-center gap-1.5">
              <Layers className="w-4 h-4 text-rose-800" />
              <span>2. Standar Pemberkasan 12 Rangkap</span>
            </div>
            <p className="text-stone-700 leading-relaxed">
              Sesuai PMK No. 2/2021, Pemohon wajib menyiapkan <strong>1 (satu) berkas asli</strong> bertanda tangan basah di atas meterai Rp10.000,- serta <strong>11 (sebelas) salinan rangkap</strong> lengkap untuk diserahkan kepada 9 Hakim Konstitusi, Panitera, dan Arsip MK.
            </p>
          </div>

          <div className="bg-white border border-stone-200 rounded-md p-4 space-y-2">
            <div className="font-bold text-stone-900 flex items-center gap-1.5">
              <FileCheck className="w-4 h-4 text-rose-800" />
              <span>3. Penomoran dan Penandaan Kode Bukti</span>
            </div>
            <p className="text-stone-700 leading-relaxed">
              Tuliskan kode bukti (misal: <strong>Bukti P-1</strong>, <strong>Bukti P-2</strong>, dst.) pada pojok kanan atas setiap lembar alat bukti. Susun urutan bukti secara kronologis dan sinkron dengan uraian Posita permohonan.
            </p>
          </div>

          <div className="bg-white border border-stone-200 rounded-md p-4 space-y-2">
            <div className="font-bold text-stone-900 flex items-center gap-1.5">
              <ExternalLink className="w-4 h-4 text-rose-800" />
              <span>4. Pendaftaran Online (SIMPEL MK) / Offline (PTSP)</span>
            </div>
            <p className="text-stone-700 leading-relaxed">
              Pengajuan dapat dilakukan secara daring 24/7 melalui portal SIMPEL MK (<strong>simpel.mkri.id</strong>) dengan mengunggah draf permohonan format PDF & Word DOCX, atau secara langsung di Loket PTSP Gedung Mahkamah Konstitusi RI, Jakarta.
            </p>
          </div>
        </div>
      </div>

      {/* Footer Navigation */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-stone-200">
        <button
          onClick={handleBackWithScroll}
          className="w-full sm:w-auto px-5 py-2.5 border border-stone-300 rounded-md text-xs font-semibold text-stone-700 hover:bg-stone-100 transition flex items-center justify-center gap-2 cursor-pointer"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Kembali ke Laporan Asesmen</span>
        </button>

        <button
          onClick={handleProceedWithScroll}
          className="w-full sm:w-auto bg-[#881337] hover:bg-[#70102e] text-white px-6 py-2.5 rounded-md text-xs font-semibold transition flex items-center justify-center gap-2 shadow-xs border border-rose-900 cursor-pointer active:scale-95"
        >
          <span>Buat Dokumen Resmi</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>

      {/* Complete Evidence Packet Modal */}
      <EvidenceCompletePacketModal
        isOpen={isPacketModalOpen}
        onClose={() => setIsPacketModalOpen(false)}
        activeCase={activeCase}
        evidenceItems={evidenceItems}
        assessment={assessment}
        sectorName={sectorName}
      />
    </div>
  );
};
